#pragma once
#include <array>
#include <string>
namespace BeetleBuzz {
	static std::array<std::string_view, 194> fortuneList{
		"Don’t hold onto things that require a tight grip.",
		"Look how far you've come.",
		"There are things in life that you can't control, and aren't supposed to.",
		"You make it look easy. The fact is it's really hard and you do it anyway.",
		"Consistently put yourself in situations that reveal what you're made of.",
		"Everything you do is your life's work.",
		"Putting yourself fully into what you do is a form of love.",
		"Be really great at what you're good at. Leave the rest to people who are really great at what you're not.",
		"Trust yourself enough to say no when something's not right and yes when it most definitely is.",
		"Set out to do something. Work really hard. Achieve an outcome that reflects what you did to get there.",
		"Say yes, then figure it out.",
		"One day you’ll look back at right now and say, \"If I got through that, I can get through anything.\" And that will truly be a gift.",
		"When the entire world is going through the exact same thing you are... Suddenly, you're not alone.",
		"Then one day you woke up and it was bright outside. And light inside.",
		"Do what you love. The rest will fall into place.",
		"Follow your heart. See what turns up.",
		"Speak good things about yourself into existence.",
		"Embrace a new narrative.",
		"Get lost in the right direction.",
		"Decide for yourself who you are. No one else gets to make that decision for you.",
		"Follow what calls you.",
		"Be humble and proud of yourself at the same time.",
		"Stop saying yes to things you don't want to do.",
		"You can't do everything by yourself. It's okay to ask for help.",
		"Fear will always be a thing. But don't let it get in your way.",
		"Make self-care a non-negotiable.",
		"Evolve as a human.",
		"Change comes from embracing the future, not fighting your past.",
		"Decisions don't determine right and wrong. They determine outcomes.",
		"Recognize yourself in others.",
		"What's good for you brings out the best in you. What's bad for you doesn't.",
		"The only person who has to believe in you is you.",
		"Self Acceptance > Self Improvement",
		"Trust the wait. Enjoy not knowing.",
		"Set yourself up to experience what you love.",
		"Turn your life upside down. On purpose.",
		"If you want to grow, you have to be willing to learn.",
		"There are no rules.",
		"Let go and let the universe do its thing.",
		"You don't have to be small for someone else to be BIG.",
		"Be kind to other human beings.",
		"Learn to be right in a way that doesn't rely on someone else to be wrong.",
		"It's not your job to fix people.",
		"Whatever you can do, you must do.",
		"Don't let anyone forever preserve you in a place in life that you were simply passing through.",
		"It's better to wait for the right answer than rush into the wrong one.",
		"If the thing you're focusing on makes you unhappy, focus on something else.",
		"Give yourself a chance to see what happens when you don't give up.",
		"Everything's gonna be cool.",
		"Good instincts are worthless if you don't follow them.",
		"Love bad things from a good distance.",
		"Change the way you look at things. They'll return the favor.",
		"Do the thing.",
		"Edit your life.",
		"Somewhere beneath all those distracting details is the best version of you.",
		"Make people see you.",
		"Accept all experiences as potentially good.",
		"Don't focus on the tributary when you need to focus on the lake.",
		"Be easily awed, not easily impressed.",
		"Protect your heart by acknowledging what it's feeling.",
		"Don't make a wish. Make a decision.",
		"Do things on purpose.",
		"Do the thing that scares you most.",
		"Everyone you'll ever meet is smarter about something than you are.",
		"Be less moved by the opinion of others.",
		"You can't fail if you're willing to.",
		"Adjust your eyes. See the same things differently.",
		"Some things are just too heavy to haul around.",
		"The first thing you should know about me is that I'm not you. A lot more will make sense after that.",
		"Heighten your vibes. Lighten your strides.",
		"Be unwilling to lie to yourself.",
		"Everything and everyone is your teacher.",
		"Love yourself hard.",
		"It's time for a good ol' fashioned adventure.",
		"Follow what you love and see what turns up.",
		"You will know it when you see it. it will know you when it sees you.",
		"I am resilient.",
		"I don't care how smart, rich, attractive or powerful you are. Just be kind and we'll be good.",
		"Your instincts know things before you do. Trust them.",
		"Note from the future: I'm not intimidated by your past.",
		"Listen for the whispers. Look for the signs.",
		"Take nothing personally.",
		"It's good to be prepared, but stay open to surprises.",
		"Win your mind. Win your life.",
		"Tune into the love frequency. Tune out everything else.",
		"Tap into your magic.",
		"Love what you do so it will love you.",
		"Practice not-so-random acts of discipline.",
		"Hurry up and fail so you can win.",
		"Don't write off good advice from people who have had bad experiences.",
		"Mad is easier than sad, but it's far less effective.",
		"When you love yourself, people who don't love you back become less interesting.",
		"If you're not where you want to be, don't stay there for too long.",
		"Sit around and wait for happiness to find you. Just kidding. Get up and fight for it for dear life.",
		"Don't take credit for your talents. Take credit for how you use them.",
		"Unlearn everything that you aren't. Relearn everything that you are.",
		"Everything that is; was first a dream.",
		"It's your duty to dream.",
		"Keep your next move quiet.",
		"Caring what other people think about you isn't a weakness. It's accepting it as fact that gets you in trouble.",
		"Be a product of your decisions, not your circumstances.",
		"Go after what you want or be happy with what you get.",
		"Let people discover you over time.",
		"Design the version of yourself you want to be. Then be it.",
		"Seek adventure.",
		"Being patient is less about waiting things out until you get your way, and more about being tolerant of what is.",
		"Stop trying to skip the struggle. You don't get to start at the part where you're winning.",
		"You're intoxicating when you do what you love.",
		"Stay focused.",
		"Be passionate and totally worth the chaos.",
		"You will see it when you believe it.",
		"Be slow to respond, not quick to react.",
		"Dare BIG. Fear small.",
		"Pay attention to where your mind wanders when you allow it to wonder.",
		"Flow with things rather than insist they flow with you.",
		"Let yourself dream again.",
		"Enter unknown territory.",
		"Don't be in a hurry in the short term for things you want to last for the long term.",
		"Let the difference between where you are and where you want to be inspire you.",
		"Unbecome everything that isn't you. Become everything that is.",
		"Take no for an answer.",
		"Switch your frequency.",
		"Pay attention to the patterns.",
		"To be found: Stop hiding.",
		"Master your worries.",
		"That point where you are about to give up but decide not to and everything starts falling into place.",
		"Be real with yourself or you can't be real with anyone else.",
		"The middle of the process is no place to determine the end of it.",
		"Being right all of the time is limiting.",
		"Pretend it's your first time.",
		"Be warm inside even when the temperature outside is cold.",
		"More money only solves the less money problem. Nothing else.",
		"Get your hopes up.",
		"Things don't always go the way you planned. Fortunately.",
		"Make the invisible visible.",
		"Follow your hunches. Explore your doubts.",
		"Give to give. Not to get.",
		"Go with what feels right even if it ends up being wrong.",
		"Love everything. Everything will love you back.",
		"Learn to say \"I don't know\" and inherit the knowledge of the world.",
		"Sweat the small stuff. The small stuff is the big stuff.",
		"Act with purpose.",
		"Consistency is the key to mastery.",
		"The quiet speaks volumes.",
		"Don't take the bait.",
		"Be quiet. Hear more.",
		"Don't be loyal to what's not loyal to you.",
		"When you make a decision, you commit to its journey.",
		"You know what to do.",
		"The only way to get there is to decide to.",
		"Treat yourself as well as you treat others.",
		"Do first. Talk second.",
		"The more you trust yourself the more you'll be able to trust others.",
		"Just because you love something doesn't make it right for you.",
		"Just show up.",
		"The truth is not confusing.",
		"Don't do other people's parts. Just do your own.",
		"Make sure to do what you love, not just what you're good at.",
		"Identify with everything. Align with nothing.",
		"People have different opinions than you. Let them.",
		"Do your thing. Let other people do theirs.",
		"You can't force a thing to work when it's not supposed to.",
		"Go outside and play.",
		"Invest less in proving why things won't work.",
		"If you want it to be a sign, let it be. If you fear it's a sign, don't let it be.",
		"Don't just plant a seed and let it grow: take pleasure in its growth.",
		"Be better at being wrong.",
		"Not getting what you want usually gives you information that you need.",
		"Roadblocks emerge to either stop you or reroute you. It's up to you whether to break through them or yield their quiet instruction.",
		"Marvel at what happens when you stop interfering.",
		"You don't need to figure it out right now.",
		"You're not courageous because you lack fear. You're courageous because you feel fear and keep going anyway.",
		"When doing something doesn't work, do something different instead.",
		"Use your power for good.",
		"Keep looking for the lessons even when you don't think you need them.",
		"Nothing means anything until you make something of nothing.",
		"Learn to distinguish between what is familiar and what is love.",
		"What others think about you doesn't define you.",
		"It's allowed to be easy.",
		"Beware the grand gesture.",
		"Consider that the opposite of your hypothesis is true.",
		"Don't confuse the learning tool with the lesson.",
		"Don't make up your mind until you're good and ready. Feel free to change it after that.",
		"Don't seek approval from others. Seek it from yourself.",
		"No sudden moves.",
		"The silent person isn't thinking what you think he is. You are.",
		"Be enough like the people that they'll listen to you. Be enough different that you'll have something to say.",
		"If you're someone who imagines but doesn't create, find someone who creates but doesn't imagine.",
		"You can't tell what someone's feeling on the inside by what they're showing on the outside.",
		"Learn as much from joy as you do from pain.",
		"Don't expect what you see in your mind to look the same in the mind of others.",
		"First impressions are overrated. It's not that they can't be accurate. It's that they're often based on things that don't matter.",
		"Learn to delay gratification.",
		"Master living in a perpetual state of not knowing. You are here.",
	};
}